window.starRingConfig = {
  bestKey: "star-ring-dodge-best",
  profileKey: "star-ring-dodge-profile",

  tuning: {
    playerRadius: 22,
    playerSpeed: 370,
    playerAcceleration: 16,
    playerDeceleration: 22,
    playerTurnLerp: 18,
    playerStopThreshold: 18,
    worldWidth: 2400,
    worldHeight: 1600,
    asteroidCullPadding: 160,
    laserCullPadding: 120,
    pickupSpawnLocalRadius: 460,
    routeGateMargin: 120,
    starCount: 90,
    laserSpeed: 720,
    laserLife: 0.9,
    shootCooldown: 0.18,
    laserSpawnOffset: 18,
    doubleShotOffset: 9,
    asteroidRadiusMin: 20,
    asteroidRadiusRange: 22,
    asteroidSpeedBase: 110,
    asteroidSpeedRange: 70,
    largeAsteroidThreshold: 34,
    eliteRadiusMultiplier: 2.05,
    eliteHp: 6,
    eliteSpeedMultiplier: 0.5,
    eliteMaxSpeedMultiplier: 0.8,
    eliteHomingAccel: 30,
    eliteFirstDelay: 16,
    eliteMinInterval: 22,
    eliteMaxActive: 1,
    eliteCullPadding: 560,
    eliteSplitCount: 3,
    eliteSplitSpeed: 165,
    eliteFragmentSafeGap: 52,
    eliteKnockback: 260,
    eliteRecoil: 90,
    scoreAsteroid: 18,
    scoreElite: 140,
    scoreCore: 25,
    safeSpawnDistance: 260,
    maxSpawnAttempts: 8,
    hitInvulnerability: 0.9,
    hitFlashDuration: 0.34,
    difficultyStep: 5.5,
    baseSpawnInterval: 1.05,
    minSpawnInterval: 0.42,
    spawnIntervalStep: 0.045,
    asteroidSpeedStep: 0.055,
    maxSpeedScale: 1.95,
    screenShakeDecay: 32,
    thrusterTrailInterval: 0.035,
    routeGateAppearDuration: 0.7,
    warpFlashDuration: 0.58,
    impactRingLife: 0.34,
    powerUpSpawnInterval: 9,
    doubleShotDuration: 8,
    pickupSafeDistance: 120,
    pickupAsteroidDistance: 132,
    maxPickupSpawnAttempts: 18,
    asteroidWarningDistance: 96,
    idleFrameInterval: 1000 / 12,
    routeChoiceInterval: 28,
    routeChoiceDuration: 11,
    routeGateRadius: 42,
    routeChoiceSpawnSlowdown: 1.8,
    visualStarTrail: 0.72,
    visualHazeStrength: 0.14,
    visualRingDepth: 0.5,
    visualShadowOffset: 8,
    visualShadowAlpha: 0.22,
    visualLaserTrail: 0.58,
    visualVignetteTint: 0.16,
    minimapSize: 150,
    minimapMargin: 14,
    minimapMobileClearance: 140
  },

  regions: {
    drift: {
      name: "安定漂流区",
      nameEn: "Stable Drift",
      label: "DRIFT",
      description: "陨石压力较低，适合调整航线。",
      descriptionEn: "Low asteroid pressure, ideal for adjusting your course.",
      tint: "98,228,255",
      secondaryTint: "123,140,255",
      asteroidSpawnMultiplier: 1.12,
      asteroidSpeedMultiplier: 0.92,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.1
    },
    belt: {
      name: "密集陨带",
      nameEn: "Dense Asteroid Belt",
      label: "BELT",
      description: "陨石更密更快，精英陨石频繁出没。",
      descriptionEn: "Asteroids are denser and faster, with elite asteroids appearing often.",
      tint: "255,111,135",
      secondaryTint: "255,181,158",
      asteroidSpawnMultiplier: 0.76,
      asteroidSpeedMultiplier: 1.14,
      coreIntervalMultiplier: 1.08,
      powerUpIntervalMultiplier: 1.1,
      eliteChance: 0.55
    },
    stream: {
      name: "核心流",
      nameEn: "Core Stream",
      label: "STREAM",
      description: "高能核心更频繁地穿过航道。",
      descriptionEn: "High-energy cores cross the flight path more frequently.",
      tint: "138,255,209",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 0.96,
      asteroidSpeedMultiplier: 0.98,
      coreIntervalMultiplier: 0.56,
      powerUpIntervalMultiplier: 1.05,
      eliteChance: 0.22
    },
    rift: {
      name: "跃迁裂隙",
      nameEn: "Warp Rift",
      label: "RIFT",
      description: "空间流速紊乱，道具补给更活跃。",
      descriptionEn: "Unstable spatial flow makes supplies more active.",
      tint: "191,132,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 0.84,
      asteroidSpeedMultiplier: 1.08,
      coreIntervalMultiplier: 0.9,
      powerUpIntervalMultiplier: 0.58,
      eliteChance: 0.38
    },
    vortex: {
      name: "引力涡流区",
      nameEn: "Gravity Vortex",
      label: "VORTEX",
      description: "空间被多股引力涡流扭曲，陨石轨迹会被弯折，注意预判。",
      descriptionEn: "Multiple gravity vortices bend asteroid trajectories. Predict their paths.",
      tint: "114,240,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 1,
      asteroidSpeedMultiplier: 1,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.3,
      mechanic: { type: "vortex", centers: 3, radius: 200, strength: 140 }
    },
    nebula: {
      name: "静默星云",
      nameEn: "Silent Nebula",
      label: "NEBULA",
      description: "浓密星云遮蔽视野，但补给刷新更快，以视野换补给。",
      descriptionEn: "Dense nebulae obscure the view, but supplies refresh faster.",
      tint: "118,128,158",
      secondaryTint: "138,150,190",
      asteroidSpawnMultiplier: 1.05,
      asteroidSpeedMultiplier: 0.95,
      coreIntervalMultiplier: 0.95,
      powerUpIntervalMultiplier: 0.6,
      eliteChance: 0.25,
      mechanic: { type: "nebula", hazeBoost: 0.18, vignetteBoost: 0.12 }
    },
    aurora: {
      name: "极光带",
      nameEn: "Aurora Belt",
      label: "AURORA",
      description: "极光在星空中流动，节奏舒缓，适合重整航线。",
      descriptionEn: "Auroras flow through the stars in a calmer rhythm for resetting your course.",
      tint: "138,120,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 1,
      asteroidSpeedMultiplier: 0.95,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1.05,
      eliteChance: 0.2
    },
    forge: {
      name: "恒星熔炉",
      nameEn: "Stellar Forge",
      label: "FORGE",
      description: "恒星活动剧烈，陨石密而快，精英频繁出没。",
      descriptionEn: "Violent stellar activity brings dense, fast asteroids and frequent elites.",
      tint: "255,166,98",
      secondaryTint: "255,96,96",
      asteroidSpawnMultiplier: 0.72,
      asteroidSpeedMultiplier: 1.18,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.5
    }
  },

  uiText: {
    zh: {
      startTitle: "按空格开始",
      startText: "方向键或 WASD 移动，J 发射激光，P 或 Esc 暂停。拾取蓝色能量核得分，存活后选择跃迁门进入不同星域。",
      startButton: "开始游戏",
      pauseTitle: "已暂停",
      pauseText: "按 P、Esc 或点击按钮继续。",
      pauseButton: "继续游戏",
      recordTitle: "刷新纪录",
      gameOverTitle: "本局结束",
      restartButton: "再来一局",
      newRecord: (score) => `你创下了 ${score} 分的新纪录，按空格可以立即再来一局。`,
      gameOver: (score) => `你的分数是 ${score}。按空格可以立即重开。`
    },
    en: {
      startTitle: "Press Space to Start",
      startText: "Move with arrows or WASD, J fires laser, P or Esc pauses. Collect blue energy cores for score, then pick a warp gate to enter a new sector.",
      startButton: "Start Game",
      pauseTitle: "Paused",
      pauseText: "Press P, Esc, or the button to continue.",
      pauseButton: "Resume",
      recordTitle: "New Record",
      gameOverTitle: "Game Over",
      restartButton: "Play Again",
      newRecord: (score) => `You set a new record of ${score}. Press Space to replay.`,
      gameOver: (score) => `Your score is ${score}. Press Space to restart.`
    }
  },

  profileUi: {
    achievementColor: "#ffd76a",
    toastLife: 1.6,
    zh: {
      achievementPrefix: "成就达成·",
      statLabelPrefix: "成就·",
      unlockedValue: "新达成",
      totalRunsLabel: "累计局数",
      totalDestroyedLabel: "累计击毁"
    },
    en: {
      achievementPrefix: "Achievement: ",
      statLabelPrefix: "Ach: ",
      unlockedValue: "Unlocked",
      totalRunsLabel: "Total Runs",
      totalDestroyedLabel: "Total Destroyed"
    }
  },

  achievements: [
    { id: "first-warp", label: "初次跃迁", labelEn: "First Warp", scope: "total", metric: "warps", threshold: 1 },
    { id: "warp-runner", label: "连续跃迁", labelEn: "Warp Runner", scope: "run", metric: "regionJunctions", threshold: 5 },
    { id: "sharpshooter", label: "神射手", labelEn: "Sharpshooter", scope: "run", metric: "accuracy", threshold: 80 },
    { id: "untouchable", label: "完好无损", labelEn: "Untouchable", scope: "run", metric: "noDamageSurvival", threshold: 120 },
    { id: "asteroid-bane", label: "陨石克星", labelEn: "Asteroid Bane", scope: "total", metric: "destroyedAsteroids", threshold: 100 },
    { id: "core-collector", label: "核心收藏家", labelEn: "Core Collector", scope: "total", metric: "collectedCores", threshold: 50 },
    { id: "regular", label: "常客", labelEn: "Regular", scope: "total", metric: "runs", threshold: 20 }
  ],

  i18n: {
    zh: {
      sector: "星域", threat: "威胁", laser: "激光", core: "核心", shield: "护盾", double: "双发",
      paused: "暂停", ready: "就绪", cooldown: "冷却", warp: "跃迁", next: "下一区", shielding: "护盾中",
      warpWindow: (s) => `跃迁窗口 ${s}s`,
      chooseGate: "选择跃迁门",
      chooseGateHint: "穿过任意跃迁门选择下一片星域",
      eliteApproach: "精英陨石接近",
      eliteBreak: (n) => `精英击破 +${n}`,
      shieldMinus: "护盾 -1", hullMinus: "船体 -1", corePlus: "核心 +25",
      shieldReady: "护盾就绪", doubleFire: "双发火力",
      finalScore: "最终分数", survivalTime: "存活时间", destroyedAsteroids: "击毁陨石",
      collectedCores: "回收核心", warps: "跃迁次数", accuracy: "命中率", eliteBreakStat: "精英击破",
      settings: "设置", close: "关闭", audio: "音频", music: "背景音乐", sfx: "音效",
      ship: "飞船外形", fighter: "战斗机", delta: "三角翼", saucer: "飞碟",
      shipColor: "飞船颜色", language: "语言", on: "开", off: "关", exit: "退出", landscape: "横屏", orientationHint: "横屏游玩视野更宽",
      gameTitle: "星环闪避", gameSubtitle: "在流动星域中机动穿梭，规避陨石流，回收高能核心，并选择跃迁门探索下一片区域。",
      scoreLabel: "分数", healthLabel: "生命", bestLabel: "最高",
      missionOverview: "任务概要", mission1Title: "探索", mission1Desc: "穿越流动星域，定期选择跃迁门进入风险与收益不同的区域。",
      mission2Title: "回收", mission2Desc: "接触蓝色能量核以获得高额分数补给，不同星域会改变资源节奏。",
      mission3Title: "火力", mission3Desc: "使用激光清除障碍，优先处理大型陨石，为跃迁选择留出空间。",
      controlsLabel: "操作", controlHint1: "方向键或 WASD 移动", controlHint2: "J 发射激光", controlHint3: "Space 开始或重开，P 或 Esc 暂停",
      tacticalView: "战术视图", touchDrag: "拖动移动", touchFire: "开火", touchPause: "暂停", newRecord: "新纪录已建立"
    },
    en: {
      sector: "SECTOR", threat: "THREAT", laser: "LASER", core: "CORE", shield: "SHIELD", double: "DOUBLE",
      paused: "PAUSED", ready: "READY", cooldown: "COOLDOWN", warp: "WARP", next: "NEXT", shielding: "SHIELDING",
      warpWindow: (s) => `WARP ${s}s`,
      chooseGate: "Choose a warp gate",
      chooseGateHint: "Cross any warp gate to pick the next sector",
      eliteApproach: "Elite asteroid near",
      eliteBreak: (n) => `Elite down +${n}`,
      shieldMinus: "SHIELD -1", hullMinus: "HULL -1", corePlus: "CORE +25",
      shieldReady: "SHIELD READY", doubleFire: "DOUBLE FIRE",
      finalScore: "Final Score", survivalTime: "Survival", destroyedAsteroids: "Asteroids",
      collectedCores: "Cores", warps: "Warps", accuracy: "Accuracy", eliteBreakStat: "Elites",
      settings: "SETTINGS", close: "Close", audio: "Audio", music: "Music", sfx: "SFX",
      ship: "Ship", fighter: "Fighter", delta: "Delta", saucer: "Saucer",
      shipColor: "Ship Color", language: "Language", on: "ON", off: "OFF", exit: "Exit", landscape: "Landscape", orientationHint: "Landscape gives a wider view",
      gameTitle: "Star Ring Dodge", gameSubtitle: "Navigate drifting sectors, dodge asteroids, collect energy cores, and warp to new regions.",
      scoreLabel: "Score", healthLabel: "Health", bestLabel: "Best",
      missionOverview: "Mission Brief", mission1Title: "Explore", mission1Desc: "Traverse drifting sectors and pick warp gates to enter regions with different risk and reward.",
      mission2Title: "Collect", mission2Desc: "Gather blue energy cores for bonus score. Different sectors change resource pacing.",
      mission3Title: "Fire", mission3Desc: "Use your laser to clear obstacles. Prioritize large asteroids to make room for warp choices.",
      controlsLabel: "Controls", controlHint1: "Arrows or WASD to move", controlHint2: "J to fire laser", controlHint3: "Space to start or restart, P or Esc to pause",
      tacticalView: "Tactical View", touchDrag: "Drag to move", touchFire: "Fire", touchPause: "Pause", newRecord: "New Record"
    }
  }
};
