window.starRingConfig = {
  bestKey: "star-ring-dodge-best",
  profileKey: "star-ring-dodge-profile",

  tuning: {
    playerRadius: 22,
    playerSpeed: 370,
    playerAcceleration: 16,
    playerDeceleration: 22,
    playerTurnLerp: 18,
    playerStopThreshold: 18,
    worldWidth: 2400,
    worldHeight: 1600,
    asteroidCullPadding: 160,
    laserCullPadding: 120,
    pickupSpawnLocalRadius: 460,
    routeGateMargin: 120,
    starCount: 90,
    laserSpeed: 720,
    laserLife: 0.9,
    shootCooldown: 0.18,
    laserSpawnOffset: 18,
    doubleShotOffset: 9,
    asteroidRadiusMin: 20,
    asteroidRadiusRange: 22,
    asteroidSpeedBase: 110,
    asteroidSpeedRange: 70,
    largeAsteroidThreshold: 34,
    eliteRadiusMultiplier: 2.05,
    eliteHp: 6,
    eliteSpeedMultiplier: 0.5,
    eliteMaxSpeedMultiplier: 0.8,
    eliteHomingAccel: 30,
    eliteFirstDelay: 16,
    eliteMinInterval: 22,
    eliteMaxActive: 1,
    eliteCullPadding: 560,
    eliteSplitCount: 3,
    eliteSplitSpeed: 165,
    eliteFragmentSafeGap: 52,
    eliteKnockback: 260,
    eliteRecoil: 90,
    scoreAsteroid: 18,
    scoreElite: 140,
    scoreCore: 25,
    safeSpawnDistance: 260,
    maxSpawnAttempts: 8,
    hitInvulnerability: 0.9,
    hitFlashDuration: 0.34,
    difficultyStep: 5.5,
    baseSpawnInterval: 1.05,
    minSpawnInterval: 0.42,
    spawnIntervalStep: 0.045,
    asteroidSpeedStep: 0.055,
    maxSpeedScale: 1.95,
    screenShakeDecay: 32,
    thrusterTrailInterval: 0.035,
    routeGateAppearDuration: 0.7,
    warpFlashDuration: 0.58,
    impactRingLife: 0.34,
    powerUpSpawnInterval: 9,
    doubleShotDuration: 8,
    pickupSafeDistance: 120,
    pickupAsteroidDistance: 132,
    maxPickupSpawnAttempts: 18,
    asteroidWarningDistance: 96,
    idleFrameInterval: 1000 / 12,
    routeChoiceInterval: 28,
    routeChoiceDuration: 11,
    routeGateRadius: 42,
    routeChoiceSpawnSlowdown: 1.8,
    visualStarTrail: 0.72,
    visualHazeStrength: 0.14,
    visualRingDepth: 0.5,
    visualShadowOffset: 8,
    visualShadowAlpha: 0.22,
    visualLaserTrail: 0.58,
    visualVignetteTint: 0.16
  },

  regions: {
    drift: {
      name: "安定漂流区",
      label: "DRIFT",
      description: "陨石压力较低，适合调整航线。",
      tint: "98,228,255",
      secondaryTint: "123,140,255",
      asteroidSpawnMultiplier: 1.12,
      asteroidSpeedMultiplier: 0.92,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.1
    },
    belt: {
      name: "密集陨带",
      label: "BELT",
      description: "陨石更密更快，精英陨石频繁出没。",
      tint: "255,111,135",
      secondaryTint: "255,181,158",
      asteroidSpawnMultiplier: 0.76,
      asteroidSpeedMultiplier: 1.14,
      coreIntervalMultiplier: 1.08,
      powerUpIntervalMultiplier: 1.1,
      eliteChance: 0.55
    },
    stream: {
      name: "核心流",
      label: "STREAM",
      description: "高能核心更频繁地穿过航道。",
      tint: "138,255,209",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 0.96,
      asteroidSpeedMultiplier: 0.98,
      coreIntervalMultiplier: 0.56,
      powerUpIntervalMultiplier: 1.05,
      eliteChance: 0.22
    },
    rift: {
      name: "跃迁裂隙",
      label: "RIFT",
      description: "空间流速紊乱，道具补给更活跃。",
      tint: "191,132,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 0.84,
      asteroidSpeedMultiplier: 1.08,
      coreIntervalMultiplier: 0.9,
      powerUpIntervalMultiplier: 0.58,
      eliteChance: 0.38
    },
    vortex: {
      name: "引力涡流区",
      label: "VORTEX",
      description: "空间被多股引力涡流扭曲，陨石轨迹会被弯折，注意预判。",
      tint: "114,240,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 1,
      asteroidSpeedMultiplier: 1,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.3,
      mechanic: { type: "vortex", centers: 3, radius: 200, strength: 140 }
    },
    nebula: {
      name: "静默星云",
      label: "NEBULA",
      description: "浓密星云遮蔽视野，但补给刷新更快，以视野换补给。",
      tint: "118,128,158",
      secondaryTint: "138,150,190",
      asteroidSpawnMultiplier: 1.05,
      asteroidSpeedMultiplier: 0.95,
      coreIntervalMultiplier: 0.95,
      powerUpIntervalMultiplier: 0.6,
      eliteChance: 0.25,
      mechanic: { type: "nebula", hazeBoost: 0.18, vignetteBoost: 0.12 }
    },
    aurora: {
      name: "极光带",
      label: "AURORA",
      description: "极光在星空中流动，节奏舒缓，适合重整航线。",
      tint: "138,120,255",
      secondaryTint: "98,228,255",
      asteroidSpawnMultiplier: 1,
      asteroidSpeedMultiplier: 0.95,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1.05,
      eliteChance: 0.2
    },
    forge: {
      name: "恒星熔炉",
      label: "FORGE",
      description: "恒星活动剧烈，陨石密而快，精英频繁出没。",
      tint: "255,166,98",
      secondaryTint: "255,96,96",
      asteroidSpawnMultiplier: 0.72,
      asteroidSpeedMultiplier: 1.18,
      coreIntervalMultiplier: 1,
      powerUpIntervalMultiplier: 1,
      eliteChance: 0.5
    }
  },

  uiText: {
    startTitle: "按空格开始",
    startText: "方向键或 WASD 移动，J 发射激光，P 或 Esc 暂停。拾取蓝色能量核得分，存活后选择跃迁门进入不同星域。",
    startButton: "开始游戏",
    pauseTitle: "已暂停",
    pauseText: "按 P、Esc 或点击按钮继续。",
    pauseButton: "继续游戏",
    recordTitle: "刷新纪录",
    gameOverTitle: "本局结束",
    restartButton: "再来一局",
    newRecord: (score) => `你创下了 ${score} 分的新纪录，按空格可以立即再来一局。`,
    gameOver: (score) => `你的分数是 ${score}。按空格可以立即重开。`
  },

  profileUi: {
    achievementPrefix: "成就达成·",
    achievementColor: "#ffd76a",
    toastLife: 1.6,
    statLabelPrefix: "成就·",
    unlockedValue: "新达成",
    totalRunsLabel: "累计局数",
    totalDestroyedLabel: "累计击毁"
  },

  achievements: [
    { id: "first-warp", label: "初次跃迁", scope: "total", metric: "warps", threshold: 1 },
    { id: "warp-runner", label: "连续跃迁", scope: "run", metric: "regionJunctions", threshold: 5 },
    { id: "sharpshooter", label: "神射手", scope: "run", metric: "accuracy", threshold: 80 },
    { id: "untouchable", label: "完好无损", scope: "run", metric: "noDamageSurvival", threshold: 120 },
    { id: "asteroid-bane", label: "陨石克星", scope: "total", metric: "destroyedAsteroids", threshold: 100 },
    { id: "core-collector", label: "核心收藏家", scope: "total", metric: "collectedCores", threshold: 50 },
    { id: "regular", label: "常客", scope: "total", metric: "runs", threshold: 20 }
  ]
};
